### ISSUE TITLE
It should be able to replace EWSF

### ISSUE THREAD

**Issue by ApourtArtt** [ApourtArtt/NostaleWidget#16]
See: https://github.com/xAfterLife/EWSF

**Comment by WallcroftUK** [comment]
i dont think this is proper feature but okay :D btw after doing that getting crash so

**Comment by ApourtArtt** [comment]
Hello,
Can you please elaborate? I have been using it in place of EWSF.EWS and it is working as it should (some people are also doing that)

**Comment by WallcroftUK** [comment]
Hi, I mean yea it can be replaced but, Source code does not include logic for keep using old EWSF even if its .dll or anyone other extension user set.

that should be first thing included in current version since its part of NosTale

**Comment by WallcroftUK** [comment]
and only tagging something in issue is not actually a fix or feature 

I just want to say that this thing should be already in, That user compile SDK and replace EWSF.EWS and rename it to EWSF.dll

**Comment by WallcroftUK** [comment]
and also i want to say if its possible i could push my private work 

Time Widget and some other stuff

**Comment by ApourtArtt** [comment]
Oh, I think I understand you now.
So actually this issue was to be able to get rid of the official EWSF.EWS - which was resolved in the commit https://github.com/ApourtArtt/NostaleWidget/commit/901db7202dc78d822b2a35d96252f40bb69a2326.
If your goal is to keep the old EWSF.EWS too, then you will need to add the logic here: https://github.com/ApourtArtt/NostaleWidget/blob/main/ClientModding/main.cpp#L209
And here: https://github.com/ApourtArtt/NostaleWidget/blob/main/ClientModding/main.cpp#L174
As done with the class Example. I understand that it can be seen as a bad decision, but I wanted it as flexible as possible (currently, you can choose to now have the EWSF.EWS, you can choose to have it, but you can also choose to do something else, like displaying something more beautiful with a loading bar etc)

Regarding your proposition of adding Time widget/other widgets, I sincerely appreciate the proposition, but this SDK is getting a huge revamp (the goal being, making this SDK more user friendly) and will come with a way to handle the widgets from a community point of view (the goal being, making it server creator friendly)
