### ISSUE TITLE
effect 0 appears

### ISSUE THREAD

**Issue by Caliwhi7** [ApourtArtt/NostaleWidget#23]
When you wearing sp + 0 you get effect 0 for sitting , attacking , arrive walkpoint etc.You get this too for other upgrades but only when you transform.
![](https://gyazo.com/2843645a1246e08075b9b227dd06fed7.gif)

https://user-images.githubusercontent.com/107277185/175389908-706dc0aa-471e-4667-b1a0-457ea58010fb.mp4

**Comment by ApourtArtt** [comment]
Thank you for the report, I was able to reproduce it - seems due to the WingManager
