### ISSUE TITLE
some modding quest

### ISSUE THREAD

**Issue by MarKYang5203** [ApourtArtt/NostaleWidget#28]
sir can i contact you ?  (discord or other)

**Comment by ApourtArtt** [comment]
Yes, here

**Comment by MarKYang5203** [comment]
im compiled , how to update client(NostaleX.exe)?

**Comment by ApourtArtt** [comment]
If you mean changing the IP, you can find it by opening NosTaleClientX.exe with an hex editor and search for "79.", change it with your IP. As it is a delphi string, the 4 bytes before "79." is the size of the string, you chould change it according to your new IP.

If you mean adding the project you created your issue on, I updated the readme by adding "3) You should rename the built DLL to EWSF.EWS and add it to NosTale folder" which will add this project to NosTale.

**Comment by MarKYang5203** [comment]
very thank sir , and i want ask the wing quest too!
can you record a privte video to me for about add new wing for exsample , thank a lot

**Comment by ApourtArtt** [comment]
It's supposed to be straight forward, you have an example here: https://github.com/ApourtArtt/NostaleWidget/blob/main/ClientModding/main.cpp#L39
It is adding a wing with ID 25 that has for effectId for the level 1, 1346.

The remaining effort is to add the effect, it is in NSeffData.NOS, I might cover it later, but as it is not really related to this project this is not my priority.
