### ISSUE TITLE
Time&Channel, Warp system

### ISSUE THREAD

**Issue by WallcroftUK** [ApourtArtt/NostaleWidget#31]
Hello will there be time widget ?
![image](https://user-images.githubusercontent.com/122221257/212720745-8c4232ed-f48b-4d71-88fd-031d94130eea.png)

and warp system ?
![image](https://user-images.githubusercontent.com/122221257/212720927-20896c80-34cc-4ea6-9da7-0ebbd25f69b0.png)

**Comment by ApourtArtt** [comment]
Hello,
The goal of this repository is not to create feature that can be used straight away, but rather a toolkit for developers who wants to create new features.
What you sent there is already possible through this project.

**Comment by WallcroftUK** [comment]
Hello i ask because you write on EPVP something about big release

**Comment by ApourtArtt** [comment]
Correct, and this "big release" will add features for developers, meaning idea/creativity and some programming skills will be required.
