### ISSUE TITLE
Identify widget to edit it 

### ISSUE THREAD

**Issue by xShut** [ApourtArtt/NostaleWidget#36]
I’ve spent a lot of time identifying widgets by their child numbers, but this process is really tedious and time-consuming. Is there a mode, or can we add a mode, to easily find an already instantiated widget? I mean, something like an inventory where we can add a label or something similar?

**Comment by ApourtArtt** [comment]
Sorry for the delay.
Yes there is such a feature.
If the class is already implemented in this SDK, you can access the name of the class through TheClass::NAME, with the help of an_object->findClasses(TheClass::NAME) you will get a vector of all the objects with that name.
Here is an example that get the inventory:
```cpp
auto handler = TLBSWidgetHandler::getNtInstance();
if (!handler)
{
   // Entwell did some modification and it is now broken
}
auto gameRoot = handler->getGameRootWidget();
if (!gameRoot)
{
   // Entwell did some modification and it is now broken
}

auto widgets = gameRoot->findClasses(TNTCharacterInventoryInfoWidget::NAME);
if (widgets.size() == 0)
{
    // Entwell did some modification and it is now broken
}
// There should be only one inventory, so you can take widgets[0]
inventory = reinterpret_cast<TNTCharacterInventoryInfoWidget*>(widgets[0]);
if (!inventory)
{
    // Same as above, strange issue, might come from the SDK - report it
}

// And now you can use the inventory
inventory->addWidget(...);
```
