### ISSUE TITLE
[QUESTION] adding new structures

### ISSUE THREAD

**Issue by CAV1S** [ApourtArtt/NostaleWidget#37]
Hi. For the last few weeks I tried to work with editing the widgets.
With my current knowledge I can modify, add or remove any part of the widget you've implemented.
The thing is that I would like to modify the widgets, whose structures haven't been added to the SDK.

I tried to add the structure on my own. I read many guides and watched many tutorials, but by far none of them really shows how to work on that in similar case.

For example:
I did a search for the visibility flag of the TNTCharacterInventoryInfoWidget. I found a pointer and, to be honest, I am stucked on the next actions I should do.
I've tried to use reclass.net to analyze the structure but I don't really know what to do next. I can choose a type like pointer, int64 etc but none of them are really related to the TEWControlWidgetEX, TNTIconWidget etc.

What should I do next? Could you provide some udemy courses, youtube videos or a books, which can help me understand what I should do next?
Thanks.

**Comment by ApourtArtt** [comment]
Hello,

First I would recommend to use [Interactive Delphi Reconstructor](https://github.com/crypto2011/IDR) as it will give you some interesting information:
- The size of the class
- The inheritence schema
- Some types that you will find in the class (this is not so accurate, but that can sometimes lead you to the right idea)
- 
I can unfortunately not send you any resources as most of what I learnt was by trying over and over again, but I can give you some tips:
- When you found the pointer to the class you want to analyze (I'd recommand to use the coordinates, as you know the offset of those variables), load it on Reclass using the starting address (the address of the "isVisible" boolean is 0x18, so if you have 0x5000018, you want to load 0x5000000 on Reclass)
- Check the inheritance schema and the size: analyze every class that you did not analyze yet, from the parent to the child.
- When there is a variable that you do not understand, try to see what reads/writes to this value (you can use Cheat Engine for that), it might leads you to the right idea (if you see string manipulation, it might be a string, ...)
- If it is still not enough, take a look at what IDR says about this offset. If it is still not enough, it is probably not important for you, skip it.

**Comment by CAV1S** [comment]
> Hello,
> 
> First I would recommend to use [Interactive Delphi Reconstructor](https://github.com/crypto2011/IDR) as it will give you some interesting information:
> 
> * The size of the class
> * The inheritence schema
> * Some types that you will find in the class (this is not so accurate, but that can sometimes lead you to the right idea)
> 
> I can unfortunately not send you any resources as most of what I learnt was by trying over and over again, but I can give you some tips:
> 
> * When you found the pointer to the class you want to analyze (I'd recommand to use the coordinates, as you know the offset of those variables), load it on Reclass using the starting address (the address of the "isVisible" boolean is 0x18, so if you have 0x5000018, you want to load 0x5000000 on Reclass)
> * Check the inheritance schema and the size: analyze every class that you did not analyze yet, from the parent to the child.
> * When there is a variable that you do not understand, try to see what reads/writes to this value (you can use Cheat Engine for that), it might leads you to the right idea (if you see string manipulation, it might be a string, ...)
> * If it is still not enough, take a look at what IDR says about this offset. If it is still not enough, it is probably not important for you, skip it.

Thanks a lot for a quick reply!

Your recommendations helped me a lot.
I managed to find the goldbar label in the TNTCharacterInventoryInfoWidget.
It is located on:
BaseModule + 4BD7DC (the TNTCharacterInventoryInfoWidget pointer)
0x20 , 0x04 -> child of the TNTCharacterInventoryInfoWidget
0x18 -> TEWLabel 
0x80 -> looks like the label's text:
![image](https://github.com/ApourtArtt/NostaleWidget/assets/53760634/a79615ab-dfc1-4be6-b37a-3bbebdc6db2a)

But tbh...I am not sure what I should do next. Let's say, I would like to change gold value to much higher amount. For that purpose I will need to increase the size of the label and move it to the left, because once I change the value, tbe text is cutted off.
I tried any of the values above the "378 Gold" text and there are multiple variables like color of the font etc but none of them really works as I intend to do.

Anyway, thanks for all the help already.
If you will have free time, check the discord message from me. Thanks in advance

**Comment by ApourtArtt** [comment]
I assume that it is a TEWLabel, let's do step by step.
The string you are willing to change is at the offset 0x80 of the TEWLabel.
Let's find it on the TEWLabel class: https://github.com/ApourtArtt/NostaleWidget/blob/main/ClientModding/Api/DelphiClasses/TEWLabel.h#L43
We have a class named TextPosition that starts from 0x78 to 0x88, so now we need to check TextPosition.
0x80-0x78 = 0x08, this is the offset of the "378 Gold" in the TextPosition.
https://github.com/ApourtArtt/NostaleWidget/blob/main/ClientModding/Api/Properties/Graphical/TextPosition.h#L68
From this, I assume that modifying this variable would be sufficient. Let's try.

```cpp

TEWLabel* your_label = ...; // pointer to 0xE5A2DD0
// 1) We want the TextPosition of this label using https://github.com/ApourtArtt/NostaleWidget/blob/main/ClientModding/Api/DelphiClasses/TEWLabel.h#L34
TextPosition& textPos = your_label->getTextPosition();

// 2) You want to modify the text using https://github.com/ApourtArtt/NostaleWidget/blob/main/ClientModding/Api/Properties/Graphical/TextPosition.h#L42
textPos.setText(L"Too much gold :)");
```
I have not tested, but that should be the way.

Also, you might need to be sure that your code run after Nostale writes on this label.
What I would have done is copying the TEWLabel, appending the copy to the parent, hiding the original, and using my copy to manage my stuff without being annoyed by Entwell's code. Here is the idea, not tested once again:

```cpp
TEWLabel* your_label = ...; // pointer to 0xE5A2DD0
TEWLabel* copy = TObject::deepCopy(your_label);
your_label->setVisible(false);
copy->getParent()->addWidget(copy);

// And now you can do whatever you want on copy, Entwell's code will not refresh copy.
```

**Comment by CAV1S** [comment]
Thanks a lot for all your help.
I managed to make this part of my goal working.
I still have few others...but it is not the right place to beg for help 😆 

If you will ever be interested in working on a private stuff, feel free to contact me on discord: .cav1s.
Of course for a fair payment.

Thanks again and I hope you are having a great week!
