### ISSUE TITLE
Problem with loading whole SDK

### ISSUE THREAD

**Issue by WallcroftUK** [ApourtArtt/NostaleWidget#39]
after passing to my friend discord.dll and EWSF.EWS compiled it just dont load but for me it works good

**Comment by ApourtArtt** [comment]
Hello,
It probably comes from some vcredist not installed on his computer, I would recommend to him to try to download all the vcredist in x32 and see if it resolves the issue. It is quite common with C++ project to have this problem.

**Comment by WallcroftUK** [comment]
even when friend have same redist like me 
nothing :/

**Comment by ApourtArtt** [comment]
=> He was sharing a debug version, fixed with a release version
